// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SynthManiaAPI.Data;

#nullable disable

namespace SynthManiaAPI.Data.Migrations
{
    [DbContext(typeof(SynthManiaContext))]
    [Migration("20231213125352_createDatabase")]
    partial class createDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SynthManiaAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageFileName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Professional-grade analog synthesizer with versatile sound shaping",
                            ImageName = "ImageMissing.jpeg",
                            Name = "SynthMaster Pro",
                            Price = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "A modular analog synthesizer for experimental sound design",
                            ImageName = "ImageMissing.jpeg",
                            Name = "Modular Madness",
                            Price = 1499.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Recreates the classic analog sounds of the 70s and 80s",
                            ImageName = "ImageMissing.jpeg",
                            Name = "Vintage Vibe 3000",
                            Price = 799.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dreamy analog synth with a wide range of atmospheric tones",
                            ImageName = "ImageMissing.jpeg",
                            Name = "Analog Dreamer Pro",
                            Price = 1299.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Blends analog warmth with digital precision for a unique sonic experience",
                            ImageName = "ImageMissing.jpeg",
                            Name = "Digital Fusion 5000",
                            Price = 1699.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Cutting-edge analog synthesizer with innovative wave exploration features",
                            ImageName = "ImageMissing.jpeg",
                            Name = "Neo Wave Explorer",
                            Price = 1499.99m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Takes you back in time with its authentic retro analog sounds",
                            ImageName = "ImageMissing.jpeg",
                            Name = "Retro Synth Wizard",
                            Price = 1099.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Powerful analog polyphonic synthesizer for lush and layered compositions",
                            ImageName = "ImageMissing.jpeg",
                            Name = "Polyphonic Powerhouse",
                            Price = 1999.99m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Crafts eerie and haunting analog textures for ambient music",
                            ImageName = "ImageMissing.jpeg",
                            Name = "Dark Ambient Drifter",
                            Price = 1399.99m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Analog synthesizer with funky filter effects for groovy soundscapes",
                            ImageName = "ImageMissing.jpeg",
                            Name = "Funky Filter Freak",
                            Price = 1199.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
